apiVersion: apps/v1
kind: Ingress
metadata:
  name: hello-back
  namespace: group-name
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: api.labs-fwjyss.walmartdigital.cl
    http:
      paths:
      - path: /zzz
        backend:
          serviceName: xxx
          servicePort: yyy
---
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: hello-back
  namespace: group-name
proxy:
  path: /
route:
  strip_path: true