apiVersion: apps/v1
kind: Ingress
metadata:
  name: hello-front
  namespace: group-name
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: group-name.labs-rneaxc.walmartdigital.cl
    http:
      paths:
      - path: /
        backend:
          serviceName: hello
          servicePort: 80
      - path: /login
        backend:
          serviceName: auth
          servicePort: 80
